version: '3.1'

services:
  db:
    container_name: bookarodb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: bookrao
      POSTGRES_USR: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432
